### ISSUE TITLE
Connect() should return an RBXScriptConnection

### ISSUE THREAD

**Issue by Gskartwii** [roblox-aurora/rbx-net#12]
That way, the connection may be disconnected in Server/ClientEvents.

**Comment by Vorlias** [comment]
Will look into adding this in. 👍

**Comment by Vorlias** [comment]
Fixed in https://github.com/roblox-aurora/rbx-net/commit/a5387e88629c0934dec0b80deb336283cce293fb

**Comment by Vorlias** [comment]
Now in version `1.0.13`
