### ISSUE TITLE
Infinite yield error

### ISSUE THREAD

**Issue by AlexNolasco** [roblox-aurora/rbx-net#17]
Using v1.1.0

```
import Net from "@rbxts/net";
let exampleOne = Net.CreateEvent("NameOfEvent");
```

Yields

```
21:31:28.973 - Infinite yield possible on 'ReplicatedStorage.rbxts_include.node_modules.net.out:WaitForChild("Instance")'
21:31:28.974 - Stack Begin
21:31:28.974 - Script 'ReplicatedStorage.rbxts_include.RuntimeLib', Line 91 - field import
21:31:28.974 - Script 'ReplicatedStorage.rbxts_include.node_modules.net.out', Line 7
21:31:28.975 - Stack End
```

Roblox studio 0.401.0.338533 (Mac)

ps: version 1.1.2 does say "Loaded rbx-net v1.0.13"

**Comment by Vorlias** [comment]
If you're running `roblox-ts@latest` (0.2.14) - You will need to install `@rbxts/net@1.2.0`.

This is because there was changes to how imports work. If you want to use newer versions of net you will have to use `roblox-ts@next`
