### ISSUE TITLE
Net v2.0.0

### ISSUE THREAD

**Issue by Vorlias** [roblox-aurora/rbx-net#23]
# Remotes
- [x] ServerEvent (v2)
   - [x] Middleware Support
   - [x] Contextual events (possibly) - e.g. send only, receive only. (Possibly just type wizardy)
- [x] ServerFunction (v2)
   - [x] Make use ServerAsyncFunction or remove entirely.
- [x] ServerAsyncFunction (v2)
   - [x] Middleware Support

# Middlewares
- [x] Type Guard Middleware
- [x] Rate Limit Middleware
- [ ] Caching Middleware?
- [x] Logging Middleware?

**Comment by Vorlias** [comment]
With v2, I'm contemplating fully removing function objects in favour of the async functions (RemoteEvent driven functions). Much friendlier for tools like NoahWillCode's event log, and also actually supports using async callbacks and calling clients.

**Comment by Vorlias** [comment]
The middleware in RbxNet is typed similarly to Rodux now.

e.g. converting an "id" to an NPC
```ts
const toNPC: Middleware<[NPCEntity], [string]> = (next) => {
    return (sender, npcId) => {
        const npc = NPCManager.GetNPCById(npcId);
        if (npc) {
            next(sender, npc); // this will send NPC as an argument
        }
        // If `next` is never called, it will silently fail. I'm considering a sort of "reject" function as well.
    }
};

const TradeWithNPC = new Net.ServerEvent("TradeWithNPC", [Net.Typed(t.string), toNPC]);
TradeWithNPC.Connect((player, npc) => {
    // npc is of type NPCEntity
});
```

**Comment by Vorlias** [comment]
I'm considering now moving the connect-related middleware to the connect function itself. Probably a more sensible option. :?

**Comment by iamacup** [comment]
Hey

A couple of points on the state of 2.x - It looks great!

* The majority of the code seems to need to be wrapped with `/* eslint-disable roblox-ts/no-any */` to stop fatal linting errors (for default rules from roblox-ts) - i assume this is because the types are not finalised yet? i might be able to help if thats the case.
* It looks like git is out of sync with NPM and/or the docs are versioned wrong - `2.0.0.alpha.7` is the latest version on master at git but NPM has `2.0.0.alpha.6`

I submited a docs-only pull request to fix up some errors in the 2.x docs as well :)

great work!

**Comment by Vorlias** [comment]
> 
> 
> Hey
> 
> A couple of points on the state of 2.x - It looks great!
> 
>     * The majority of the code seems to need to be wrapped with `/* eslint-disable roblox-ts/no-any */` to stop fatal linting errors (for default rules from roblox-ts) - i assume this is because the types are not finalised yet? i might be able to help if thats the case.
> 
>     * It looks like git is out of sync with NPM and/or the docs are versioned wrong - `2.0.0.alpha.7` is the latest version on master at git but NPM has `2.0.0.alpha.6`
> 
> 
> I submited a docs-only pull request to fix up some errors in the 2.x docs as well :)
> 
> great work!

Haven't run into any linting issues with the roblox-ts linter, although it is a bit buggy and usually requires a restart if that happens.

The NPM version should be updated to 2.0.0-rc.0 in a moment. This should be a more akin to what the release will look like. (which includes changes from `.7`)
