### ISSUE TITLE
Global middleware

### ISSUE THREAD

**Issue by grilme99** [roblox-aurora/rbx-net#32]
Right now there is no way to make a piece of middleware apply to all remotes in a `Definition`. This would be useful for applications such as logging or analytics; I want to track how much data is going through remotes and at what frequency in production.

Maybe when creating a `Definition` you could also pass in an array of `Middleware` as a second parameter. Something like the following:
```typescript
Net.Definitions.Create({
    SomeEvent = Net.Definitions.Event()
}, [
    Net.Definitions.ReadonlyMiddleware((remoteName, remoteData) => {
        // Do something
    })
])
```

**Comment by Vorlias** [comment]
Looking into the implementation for this now 👍🏻

**Comment by Vorlias** [comment]
So the plan is that the global middleware gets pushed onto the end of the local middleware (if any) for each remote created.

This means that it should run after any local middleware. Let me know if you want it to run first (if that's preferable)

**Comment by grilme99** [comment]
Running after is perfectly fine with me!
