### ISSUE TITLE
Explicit definitions API overhaul

### ISSUE THREAD

**Issue by Vorlias** [roblox-aurora/rbx-net#35]
Deprecate `Net.Definitions.Event` for `Net.Definitions.ServerEvent`, `Net.Definitions.ClientEvent`.

The difference here is 

`ServerEvent` - An event _fired_ by the server and received by a client.
`ClientEvent` - An event _fired_ by the client and recieved by the server.

The typings are updated so 

A `ServerEvent` grabbed on the server can only _fire_, and on the client can only _recieve_. 
A `ClientEvent` on the server can only _recieve_ and on the client can only _fire_.

This is only a typing difference, behaviorally for Luau it would not matter.

I'm not sure on the naming schemes here though. Are they too ambiguous? what would work better?

**Comment by Vorlias** [comment]
I'm also contemplating breaking down AsyncFunction into Server/Client too for the same sort of isolation. `Function` will stay the same as it only works one way anyway.

**Comment by OverHash** [comment]
I support the motion to isolate the events like this, but am dubious of the naming. Adding `Client*` implies that the event is only to be used on the client. Maybe a different prefix should be found.

Additionally, how would you define a bidirectional remote? Or are you going with the idea to not allow that behaviour?

**Comment by Vorlias** [comment]
> 
> 
> I support the motion to isolate the events like this, but am dubious of the naming. Adding `Client*` implies that the event is only to be used on the client. Maybe a different prefix should be found.
> 
> Additionally, how would you define a bidirectional remote? Or are you going with the idea to not allow that behaviour?

Do you have an example of a bidirectional remote that wouldn't be achievable with AsyncFunction ?

Also yeah the naming I'm still iffy about myself, I am wanting to find alternatives - could do things like `ClientToServerEvent` and `ServerToClientEvent` or something, but still don't know about that.

**Comment by OverHash** [comment]
An example of a bidirectional event that I use in my game is when someone adds/removes an item from trading. The client will tell the server, and then the server will fire off to the other player.

It would be good to support these use cases.

Having verbose names like `ClientToServerEvent` is not a bad idea.

**Comment by Vorlias** [comment]
> 
> 
> An example of a bidirectional event that I use in my game is when someone adds/removes an item from trading. The client will tell the server, and then the server will fire off to the other player.
> 
> It would be good to support these use cases.
> 
> Having verbose names like `ClientToServerEvent` is not a bad idea.

Could have `BidirectionalEvent` perhaps, since that's more descriptive for that?

**Comment by OverHash** [comment]
Yep, thought that was a good name too.

**Comment by Vorlias** [comment]
Members added: 
`Net.Definitions.BidirectionalEvent`
`Net.Definitions.ServerToClientEvent`
`Net.Definitions.ClientToServerEvent`
`Net.Definitions.CallServerAsyncFunction`
`Net.Definitions.CallServerFunction`
`Net.Definitions.CallClientAsyncFunction`

Deprecated (and will be removed in 2.2):
`Net.Definitions.Event`
`Net.Definitions.Function`
`Net.Definitions.AsyncFunction`

**Comment by Vorlias** [comment]
I did think about prefixing them with `Define` but it might make those names too long.
