### ISSUE TITLE
Rate limiting features

### ISSUE THREAD

**Issue by Dog2puppy** [roblox-aurora/rbx-net#4]
For requests that use data stores or other APIs with rate limits, it would be useful to be able to implement throttles and rate limits on the events and functions using those APIs. For example, you could rate limit a RemoteFunction that gets profile data from data stores so that there's only 2 requests per 10 seconds, and other requests can be queued or dropped.

**Comment by Vorlias** [comment]
`ServerFunction.ClientCache` can be used to cache results for RemoteFunctions.

The value is the amount of seconds the value is cached for. Does that suffice?

**Comment by Dog2puppy** [comment]
Does the cache feature call the server if different parameters are used?

**Comment by Vorlias** [comment]
It will cache regardless of the parameters provided... unlike ModRemote where you can cache based on the first parameter.

If you want, I can also add that functionality into rbx-net.

**Comment by Vorlias** [comment]
I can add a rate limit system as well 👍

**Comment by Vorlias** [comment]
Had to create a separate class, because I need a wrapper callback to handle rate limitations.

https://github.com/roblox-aurora/rbx-net/blob/rate-limitation/src/index.ts#L313-L362

How does this look for you? Works good. I'll work on adding an event equivalent as well.

**Comment by Dog2puppy** [comment]
Skimming through it, it looks good! 👍
