### ISSUE TITLE
Deferred events causes remotes to not be found in Studio

### ISSUE THREAD

**Issue by dantheprogram** [roblox-aurora/rbx-net#48]
Here's a quick example:
```typescript
// main.client.ts
import { Remotes } from "shared/remotes";
const PrintMessage = Remotes.Client.Get("PrintMessage");
PrintMessage.SendToServer("Hello there!");
```

```typescript
// remotes.ts
import Net from "@rbxts/net";
export const Remotes = Net.Definitions.Create({
	PrintMessage: Net.Definitions.ClientToServerEvent<[message: string]>(),
});
```

```typescript
// main.client.ts
import { Remotes } from "shared/remotes";
const PrintMessage = Remotes.Server.Create("PrintMessage");
PrintMessage.Connect((player, message) => {
	print(`Server recieved message: ${message} from player: ${player}`);
});
```

With `Workspace.SignalBehavior` set to `Immediate`, the server prints `Server recieved message: Hello there! from player: Player` as expected. However, with `Workspace.SignalBehavior` set to `Deferred`,  the client *might* throw the following error:
`ReplicatedStorage.rbxts_include.node_modules.net.out.internal:188: Could not find Remote of type RemoteEvent called "PrintMessage"`

**Comment by Vorlias** [comment]
This should not be as much of an issue anymore if you're using 2.1.5 (yields on Get) or 3.0 (yields on Get by default).
