### ISSUE TITLE
Docs don't cover GameMessagingEvent

### ISSUE THREAD

**Issue by hero-ku** [roblox-aurora/rbx-net#49]

**Comment by Vorlias** [comment]
This wasn't really officially supported in Net, however in v3.0 will be and will be properly documented when that's released.

**Comment by Vorlias** [comment]
v3.0 will be introducing `Net.Definitions.ExperienceBroadcastEvent`, as well as potentially its replicating counterpart analogous to `GameMessagingEvent`.
