### ISSUE TITLE
No ErrorHandler for when Middleware.TypeChecking fails

### ISSUE THREAD

**Issue by sasial-dev** [roblox-aurora/rbx-net#59]
I can attach an ErrorHandler for Middleware.RateLimit but not for Middleware.TypeChecking

**Comment by Vorlias** [comment]
You can do this by doing

```ts
const typeChecker = Net.Middleware.TypeChecking(...checks).WithErrorHandler(errorHandler)
```

This is definitely something I will end up documenting properly.
