### ISSUE TITLE
Client lockup hard to debug

### ISSUE THREAD

**Issue by FirstVertex** [roblox-aurora/rbx-net#66]
Experiencing a lockup when using this lib in the following scenario:

shared/netMessages.ts has a defintion for a `ServerToClientEvent`
client/homeGui.client.ts has a `Remotes.Client.Get()` for that same event

I forgot to implement any server side `Remotes.Server.Create()` for this event.  So that was my mistake.

But in this scenario, my app silently fails to load, never throws an error, and sits there doing nothing.

To track it down I had to add print() statements in all the chain of imports until I facepalmed when I discovered the unconnected event.

Previously, I have seen an error message from rbx-net in a similar situation, but I think it was actually the opposite, where the Server had tried to send an event, and Client code was not yet written for that.  It has a timeout that waits a number of seconds before displaying a warning.  Similar behavior in the above-mentioned opposite bug would have been very much appreciated.

**Comment by Vorlias** [comment]
It's recommended to use v3.0 now, it will automatically create the remotes regardless.
