### ISSUE TITLE
Attempt to call a nil value when Net.CreateDefinitions

### ISSUE THREAD

**Issue by iUnstable0** [roblox-aurora/rbx-net#70]
this is my Remotes moduleScript in replicated storage
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Net = require(ReplicatedStorage:WaitForChild("build.rbxnet.luau"))

local Remotes = Net.CreateDefinitions({
	Ping = Net.Definitions.ServerFunction({
		Net.Middleware.RateLimit({
			MaxRequestsPerMinute = 30
		})
	}),
})

return Remotes
```

The error says it all, line 5 attempt to call a nil value
![Screen Shot 2022-05-30 at 9 36 09 PM](https://user-images.githubusercontent.com/46888825/171014341-4ceb3371-043c-4291-8c91-a4d3a4cd7c6f.png)

this is the module in replicated storage

**Comment by Vorlias** [comment]
It appears you're using the releases model of the library, which is on 2.1.x. The right code would be `Net.Definitions.Create`. `Net.CreateDefinitions` was added in 3.0.
