### ISSUE TITLE
Attempt to call a nil value (upvalue 'GeneratePlate')

### ISSUE THREAD

**Issue by cezeulor** [roblox-aurora/rbx-net#71]
Hello, I have been trying to find out what the error is but I can not know, I would appreciate it very much if you help me :

![error](https://user-images.githubusercontent.com/106556095/171220767-654713d8-5fe9-409a-9039-f258804651f4.jpg)
![Code](https://user-images.githubusercontent.com/106556095/171220773-8c5e7453-01f2-4bbd-b3e5-1d2fb5159e4f.PNG)
D

**Comment by Vorlias** [comment]
Sorry, can't help you with this. This isn't the right repository for what you're trying to get help for.

This is a networking library for the Roblox platform, not FiveM.
