### ISSUE TITLE
Add configurable location for _NetManaged folder.

### ISSUE THREAD

**Issue by MayGo** [roblox-aurora/rbx-net#78]
Currently, definitions are created into this library source code:
<img width="304" alt="Screenshot 2022-09-08 at 11 36 36" src="https://user-images.githubusercontent.com/1929299/189076048-051bd7ab-771c-4e6d-83db-5e02d64df4e2.png">

Can we make Parent configurable? 
https://github.com/roblox-aurora/rbx-net/blob/5cde00453e868c97488b53305053106a3c10214a/src/internal/index.ts#L88

Would like that _NetManaged folder would be directly under ReplicatedStorage
ReplicatedStorage->_NetManaged->toggleCampaignStartButton

Little bit of background:

I want to implement code Hot Reloading and current problem is that _NetManaged folders gets removed, if I run Rojo and files are synced.

**Comment by MayGo** [comment]
Tested this change out locally. And it would not fix my situation.
It is because of rojo. https://github.com/rojo-rbx/rojo/issues/559

**Comment by Vorlias** [comment]
This was an intentional design decision because it prevents any potential weird behaviour where two incompatible versions of Net might be in your project (e.g. another version from a package)
