### ISSUE TITLE
Why is my Remotes.Server.OnFunction complaining about Argument of type 'string' is not assignable to parameter of type 'never'?

### ISSUE THREAD

**Issue by dev-syn** [roblox-aurora/rbx-net#93]
Remotes.ts:

```ts
import Net, { Definitions } from '@rbxts/net';
import type { SerializedCharacter } from '../types/Serialized/SerializedCharacter';

const Remotes = Net.CreateDefinitions({
    GetCharacters: Definitions.ServerFunction<(player: Player) => SerializedCharacter[]>()
});

export = Remotes;
```

main.server.ts:

```ts
import Remotes from 'shared/Remotes';
import type { SerializedCharacter } from '../types/Serialized/SerializedCharacter';

Remotes.Server.OnFunction('GetCharacters',(player: Player) => {
    return [];
});

```

![image_2023-12-10_070241897](https://github.com/roblox-aurora/rbx-net/assets/103451081/48e7e42b-ce38-4abe-8c39-6e3a8b78a550)

![image_2023-12-10_070342989](https://github.com/roblox-aurora/rbx-net/assets/103451081/4fe777c3-fc0d-4d3a-bd44-f5e04a742b09)

**Comment by dev-syn** [comment]
Though I am able to get it to work with the Remotes.Server.Get()

```ts
import Remotes from 'shared/Remotes';
import type { SerializedCharacter } from '../types/Serialized/SerializedCharacter';

Remotes.Server.Get('GetCharacters').SetCallback((player: Player) => {
    return [];
});

Remotes.Server.OnFunction('GetCharacters',(player: Player) => {
    return [];
});
```

**Comment by OverHash** [comment]
I wasn't aware that `Remotes.Server` was still around. Using `.Get` is the recommended way to do things.

**Comment by dev-syn** [comment]
> I wasn't aware that `Remotes.Server` was still around. Using `.Get` is the recommended way to do things.

Ok I only was lead to OnFunction because `Remotes.Server.Get()` was pointing to `Remotes.Server.OnFunction()` as a better alternative but I will just use `Get` then.
